language: cpp

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libcurl4-openssl-dev

env:
 - HTTP_CONN=YES SOCKET_CONN=YES
 - HTTP_CONN=NO SOCKET_CONN=NO

compiler:
  - clang
  - gcc

script: cd build && cmake -DHTTP_CONNECTOR=${HTTP_CONN} -DSOCKET_CONNECTOR=${SOCKET_CONN} .. && make && make test
